### PR TITLE
So installguide

### PR DESCRIPTION
**Pull request by swapnilogale**

### CODE REVIEW

**Comment by swapnilogale** [comment]
@archaeogeek - can you have a quick look at these topics I've reviewed?

**Comment by archaeogeek** [comment]
@swapnilogale thursday at the earliest for me. You could try asking @pvgenuchten to review?

**Comment by archaeogeek** [comment]
This needs reviewing in the light of the changes suggested in https://github.com/geonetwork/doc/pull/122

**Comment by pvgenuchten** [comment]
Thanx @swapnilogale and @archaeogeek for the work, sorry for keeping it open for so long

**Pull request merged**
