### PR TITLE
Adds WAR configuration option for maxUploadSize

### PR DESCRIPTION
**Pull request by michikommader**
In case you want to update `maxUploadSize` for an already deployed WAR or prior to deploying.

### CODE REVIEW

**Comment by jodygarnett** [comment]
This PR was still open? It missed out on the mkdocs conversion ... can you make this change to core-geonetwork please

**Comment by michikommader** [comment]
I still see this PR as reasonable documentation extension on filestore configuration for uploading of attachments.

It is a very common use case that you want to upload attachments which exceed 100 Mb. If you want to change this size constraint for an *already deployed* service, the docs are missing an explanation on how to accomplish it. Currently, the docs only tell you how to configure the default value *prior* to deploying. My PR fixes that by adding the missing information.

**Comment by jodygarnett** [comment]
Great! Can you make this PR for the docs which are now moved to core-geonetwork repo

**Comment by michikommader** [comment]
This PR has been moved to `core-geonetwork` repository.

**Pull request closed without merging**
