### PR TITLE
Add page on style-guide

### PR DESCRIPTION
**Pull request by archaeogeek**
Incomplete, but replaces https://github.com/geonetwork/doc/wiki/Documentation-Style-Guide-(WIP)

### CODE REVIEW

**Comment by fxprunayre** [comment]
How does the "pull bot" work ? it looks like it forced push and removed you changes ?

**Comment by archaeogeek** [comment]
Try now

**Comment by fxprunayre** [comment]
LGTM, do you want to merge it as it is for now or do you want to add more details?

Then you can link to that page in the wiki https://github.com/geonetwork/doc/wiki/Documentation-Style-Guide-(WIP)

**Comment by archaeogeek** [comment]
@fxprunayre Let's merge now, I can't think off the top of my head of all the different terms we might want to include here...

**Pull request merged**
