### PR TITLE
Fixing a couple of typos in creating-custom-editor

### PR DESCRIPTION
**Pull request by archaeogeek**

### CODE REVIEW

**Comment by fxprunayre** [comment]
Your fix should go in https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L29 and then you apply https://geonetwork-opensource.org/manuals/trunk/en/contributing/writing-documentation.html#building-the-standards-docs

**Comment by archaeogeek** [comment]
@fxprunayre I'm confused because what's in https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd doesn't totally match what's in https://geonetwork-opensource.org/manuals/trunk/en/customizing-application/editor-ui/creating-custom-editor.html. Particularly at https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L1670 it seems to stop matching all together!

**Comment by fxprunayre** [comment]
> it seems to stop matching all together!

Lines https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L1670-L1674 are in the HTML no ?
Maybe there is some issue while building the doc https://github.com/geonetwork/core-geonetwork/blob/master/docs/schema-doc/src/main/resources/config-editor-doc.xsl

What is the difference you found ?

**Comment by archaeogeek** [comment]
The following screenshot comes from https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L1637-L1664:

Screenshot from 2020-04-06 13-53-24

which is followed by 
Screenshot from 2020-04-06 13-56-15

but the snippet that follows in https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L1670-L1674 appears in a completely different section of the html:

Screenshot from 2020-04-06 13-58-06

also (eg) https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L2170 doesn't appear in that page at all afaict

**Comment by fxprunayre** [comment]
Ordering is set by https://github.com/geonetwork/core-geonetwork/blob/master/docs/schema-doc/src/main/resources/config-editor-doc.xsl#L33.
We focus first on `xs:element` (https://github.com/geonetwork/core-geonetwork/blob/master/docs/schema-doc/src/main/resources/config-editor-doc.xsl#L43) which contains :
* local `xs:attribute`
* ref to `xs:attribute`
* then is composed of a `xs:sequence`



> also (eg) https://github.com/geonetwork/core-geonetwork/blob/master/schemas/config-editor.xsd#L2170 doesn't appear in that page at all afaict

Maybe we simply have to run the build for updating it.

**Comment by pvgenuchten** [comment]
closing this, as should be applied elsewhere

**Pull request closed without merging**
